name: dataset-caucasus-gchem-2023
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=1.5.1
  - matplotlib
  - ipykernel
  - jupyter
  - openpyxl
  - pypdf
  - cmcrameri
  - xlrd
  - pip
  - pip:
      - git+https://github.com/dyvasey/geoscripts.git@v0.3.0
